config:
  credentials:
  - id: synergy_dockerhub_bot_pass
    password_var: JPL_DOCKERPASS
    username_var: JPL_DOCKERUSER
  project_repos: {}
environment:
  JPL_DOCKERPUSH: saps-common-build
sqa_criteria:
  qc_doc:
    repos:
      this_repo:
        commands:
        - pip install recommonmark
        - make html -C docs/
        container: saps-common-docs
  qc_security:
    repos:
      this_repo:
        commands:
        - mvn -f pom.xml -fn -B -DskipTests clean package com.github.spotbugs:spotbugs-maven-plugin:check
        container: saps-common-testing
  qc_style:
    repos:
      this_repo:
        commands:
        - mvn -f pom.xml spotless:check
        container: saps-common-testing
  qc_coverage:
    repos:
      this_repo:
        commands:
        - mvn -f pom.xml -B -DskipTests clean package
        - mvn -f pom.xml test
        container: saps-common-testing
timeout: 600
