services:
  common-build:
    build:
      args: {}
      context: .
      dockerfile: ./docker/Dockerfile
    command: sleep 6000000
    image: eoscsynergyapps/saps-common
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  common-docs:
    command: sleep 6000000
    image: sphinxdoc/sphinx
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  common-testing:
    command: sleep 6000000
    image: maven:3-alpine
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
